[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
  "php artisan storage:link"
]

[start]
cmd = "php artisan config:clear && php artisan route:clear && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
